// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Carreira documents */
interface CareerDocumentData {
    /**
     * Título field in *Carreira*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Digite o título da vaga
     * - **API ID Path**: career.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Requisitos field in *Carreira*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: career.requirements[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    requirements: prismicT.GroupField<Simplify<CareerDocumentDataRequirementsItem>>;
    /**
     * Desejáveis field in *Carreira*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: career.desirable[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    desirable: prismicT.GroupField<Simplify<CareerDocumentDataDesirableItem>>;
}
/**
 * Item in Carreira → Requisitos
 *
 */
export interface CareerDocumentDataRequirementsItem {
    /**
     * Requisito field in *Carreira → Requisitos*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Digite um requisito da vaga
     * - **API ID Path**: career.requirements[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item: prismicT.RichTextField;
}
/**
 * Item in Carreira → Desejáveis
 *
 */
export interface CareerDocumentDataDesirableItem {
    /**
     * Desejável field in *Carreira → Desejáveis*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Digite uma característica desejável
     * - **API ID Path**: career.desirable[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item: prismicT.RichTextField;
}
/**
 * Carreira document from Prismic
 *
 * - **API ID**: `career`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CareerDocumentData>, "career", Lang>;
/** Content for Carrossel documents */
interface CarouselDocumentData {
    /**
     * Slice Zone field in *Carrossel*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CarouselDocumentDataSlicesSlice>;
}
/**
 * Slice for *Carrossel → Slice Zone*
 *
 */
type CarouselDocumentDataSlicesSlice = BannerSlice;
/**
 * Carrossel document from Prismic
 *
 * - **API ID**: `carousel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarouselDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CarouselDocumentData>, "carousel", Lang>;
/** Content for Perguntas Frequentes documents */
interface FaqDocumentData {
    /**
     * Pergunta chave field in *Perguntas Frequentes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Qual a pergunta mais frequente?
     * - **API ID Path**: faq.key_question
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    key_question: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Perguntas Frequentes*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FaqDocumentDataSlicesSlice>;
}
/**
 * Slice for *Perguntas Frequentes → Slice Zone*
 *
 */
type FaqDocumentDataSlicesSlice = PerguntasSlice;
/**
 * Perguntas Frequentes document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;
/** Content for Projeto documents */
interface ProjectDocumentData {
    /**
     * Título field in *Projeto*
     *
     * - **Field Type**: Title
     * - **Placeholder**: título do projeto
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * descrição field in *Projeto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Descrição do projeto
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Categoria field in *Projeto*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: project.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    category: prismicT.SelectField<"Grupo Geradores" | "Energia Solar" | "Manutenção" | "Aviação">;
    /**
     * Capa field in *Projeto*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Projeto*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
}
/**
 * Slice for *Projeto → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = ArtigoSlice;
/**
 * Projeto document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
export type AllDocumentTypes = CareerDocument | CarouselDocument | FaqDocument | ProjectDocument;
/**
 * Primary content in Artigo → Primary
 *
 */
interface ArtigoSliceDefaultPrimary {
    /**
     * Título field in *Artigo → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Adicione um subtítulo
     * - **API ID Path**: artigo.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Imagem field in *Artigo → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: artigo.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in Artigo → Items
 *
 */
export interface ArtigoSliceDefaultItem {
    /**
     * Parágrafo field in *Artigo → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Adicione o conteúdo de seu projeto
     * - **API ID Path**: artigo.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Default variation for Artigo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Artigo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtigoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArtigoSliceDefaultPrimary>, Simplify<ArtigoSliceDefaultItem>>;
/**
 * Slice variation for *Artigo*
 *
 */
type ArtigoSliceVariation = ArtigoSliceDefault;
/**
 * Artigo Shared Slice
 *
 * - **API ID**: `artigo`
 * - **Description**: `Artigo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtigoSlice = prismicT.SharedSlice<"artigo", ArtigoSliceVariation>;
/**
 * Primary content in Banner → Primary
 *
 */
interface BannerSliceDefaultPrimary {
    /**
     * Título field in *Banner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Digite o título do banner
     * - **API ID Path**: banner.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Descrição field in *Banner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Digite a descrição do banner
     * - **API ID Path**: banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Plano de fundo field in *Banner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background: prismicT.ImageField<never>;
    /**
     * Link field in *Banner → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: https://ottoset.com.br/servicos#grupo-geradores
     * - **API ID Path**: banner.primary.navTo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navTo: prismicT.LinkField;
}
/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BannerSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Banner*
 *
 */
type BannerSliceVariation = BannerSliceDefault;
/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismicT.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Primary content in Perguntas → Primary
 *
 */
interface PerguntasSliceDefaultPrimary {
    /**
     * Categoria field in *Perguntas → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Preencha a categoria das perguntas
     * - **API ID Path**: perguntas.primary.category
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    category: prismicT.KeyTextField;
}
/**
 * Item in Perguntas → Items
 *
 */
export interface PerguntasSliceDefaultItem {
    /**
     * Pergunta field in *Perguntas → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Qual a pergunta?
     * - **API ID Path**: perguntas.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    question: prismicT.TitleField;
    /**
     * Resposta field in *Perguntas → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Preencha a resposta da sua pergunta
     * - **API ID Path**: perguntas.items[].answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    answer: prismicT.RichTextField;
}
/**
 * Default variation for Perguntas Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Perguntas`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PerguntasSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PerguntasSliceDefaultPrimary>, Simplify<PerguntasSliceDefaultItem>>;
/**
 * Slice variation for *Perguntas*
 *
 */
type PerguntasSliceVariation = PerguntasSliceDefault;
/**
 * Perguntas Shared Slice
 *
 * - **API ID**: `perguntas`
 * - **Description**: `Perguntas`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PerguntasSlice = prismicT.SharedSlice<"perguntas", PerguntasSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CareerDocumentData, CareerDocumentDataRequirementsItem, CareerDocumentDataDesirableItem, CareerDocument, CarouselDocumentData, CarouselDocumentDataSlicesSlice, CarouselDocument, FaqDocumentData, FaqDocumentDataSlicesSlice, FaqDocument, ProjectDocumentData, ProjectDocumentDataSlicesSlice, ProjectDocument, AllDocumentTypes, ArtigoSliceDefaultPrimary, ArtigoSliceDefaultItem, ArtigoSliceDefault, ArtigoSliceVariation, ArtigoSlice, BannerSliceDefaultPrimary, BannerSliceDefault, BannerSliceVariation, BannerSlice, PerguntasSliceDefaultPrimary, PerguntasSliceDefaultItem, PerguntasSliceDefault, PerguntasSliceVariation, PerguntasSlice };
    }
}
