// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Projeto documents */
interface ProjectDocumentData {
    /**
     * Categoria field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Categoria do Projeto
     * - **API ID Path**: project.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    category: prismicT.KeyTextField;
    /**
     * Título field in *Projeto*
     *
     * - **Field Type**: Title
     * - **Placeholder**: título do projeto
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * descrição field in *Projeto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Descrição do projeto
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Capa field in *Projeto*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Projeto*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
}
/**
 * Slice for *Projeto → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = ArtigoSlice;
/**
 * Projeto document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
export type AllDocumentTypes = ProjectDocument;
/**
 * Primary content in Artigo → Primary
 *
 */
interface ArtigoSliceDefaultPrimary {
    /**
     * Título field in *Artigo → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Adicione um subtítulo
     * - **API ID Path**: artigo.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Imagem field in *Artigo → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: artigo.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in Artigo → Items
 *
 */
export interface ArtigoSliceDefaultItem {
    /**
     * Parágrafo field in *Artigo → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Adicione o conteúdo de seu projeto
     * - **API ID Path**: artigo.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Default variation for Artigo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Artigo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtigoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArtigoSliceDefaultPrimary>, Simplify<ArtigoSliceDefaultItem>>;
/**
 * Slice variation for *Artigo*
 *
 */
type ArtigoSliceVariation = ArtigoSliceDefault;
/**
 * Artigo Shared Slice
 *
 * - **API ID**: `artigo`
 * - **Description**: `Artigo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtigoSlice = prismicT.SharedSlice<"artigo", ArtigoSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ProjectDocumentData, ProjectDocumentDataSlicesSlice, ProjectDocument, AllDocumentTypes, ArtigoSliceDefaultPrimary, ArtigoSliceDefaultItem, ArtigoSliceDefault, ArtigoSliceVariation, ArtigoSlice };
    }
}
