// Code generated by Slice Machine. DO NOT EDIT.

import Artigo from './Artigo';
import Banner from './Banner';
import Perguntas from './Perguntas';

export { Artigo, Banner, Perguntas };

export const components = {
  artigo: Artigo,
  banner: Banner,
  perguntas: Perguntas,
};
