// Code generated by Slice Machine. DO NOT EDIT.

import Artigo from './Artigo';
import Perguntas from './Perguntas';

export {
	Artigo,
	Perguntas,
};

export const components = {
	artigo: Artigo,
	perguntas: Perguntas,
};
